name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository on the virtual machine
        uses: actions/checkout@v4
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-angular-app
    steps:
      - name: Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          source: dist/portfolio
          target: /home/gutovnet/repositories/portfolio
