name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository on the virtual machine
        uses: actions/checkout@v4
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build -- --output-path=dist/build

  deploy:
    runs-on: ubuntu-latest
    needs: build-angular-app
    steps:
      - name: Sync folders and files to the server
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_SERVER }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "dist/build"
          dist_target_dir: "/repositories/portfolio"
